<?php

namespace Pizza\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pizza\CustomerBundle\Entity\Customer;

/**
 * CustomerOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderRepository extends EntityRepository
{
    public function getLatestestOrderId(Customer $customer)
    {
        $dql = "SELECT co.id FROM PizzaCustomerBundle:CustomerOrder co " .
               "WHERE co.customer = :customer ORDER BY co.createdAt DESC";
        return  $this->getEntityManager()
                ->createQuery($dql)
                ->setParameter('customer', $customer)   
                ->setMaxResults(1)
                ->setFirstResult(0)
                ->getResult()[0]['id'];
        
        
    }
    
}
