<?php

namespace Pizza\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemRepository extends EntityRepository
{
}
